In [1]:
'''Import needed modules for kaggle data download'''
#import os
#kaggle_data={"username":"","key":""}
#os.environ['KAGGLE_USERNAME']=kaggle_data["username"]
#os.environ['KAGGLE_KEY']=kaggle_data["key"]
#import kaggle

'Import needed modules for kaggle data download'

In [2]:
'''Download the data'''
#kaggle.api.dataset_download_files("tobycrabtree/nfl-scores-and-betting-data", path="./", unzip=True, quiet=False)

'Download the data'

In [3]:
'''Import modules for data cleaning'''
import pandas as pd
import numpy as np

In [4]:
teams = pd.read_csv("data/nfl_teams.csv")
stadiums = pd.read_csv("data/nfl_stadiums.csv", encoding='unicode_escape')
games =  pd.read_csv("data/spreadspoke_scores.csv")

In [5]:
stadiums.head()

,stadium_name,stadium_location,stadium_open,stadium_close,stadium_type,stadium_address,stadium_weather_station_zipcode,stadium_weather_type,stadium_capacity,stadium_surface,stadium_weather_station,stadium_weather_station_name,stadium_latitude,stadium_longitude,stadium_azimuthangle,stadium_elevation
0,Acrisure Stadium,"Pittsburgh, PA",2001.0,NaN,outdoor,"100 Art Rooney Ave, Pittsburgh, PA 15212",15212,cold,"65,500",Grass,USW00094823,"PITTSBURGH ASOS, PA US",40.484600,-80.214400,NaN,366.7
1,Alamo Dome,"San Antonio, TX",NaN,NaN,indoor,"100 Montana St, San Antonio, TX 78203",78203,indoor,72000,FieldTurf,NaN,NaN,29.416944,-98.478889,0.0,NaN
2,Allegiant Stadium,"Paradise, NV",2020.0,NaN,indoor,NaN,NaN,indoor,65000,Grass,NaN,NaN,36.090750,-115.183722,0.0,NaN
3,Allianz Arena,"Munich, Germany",NaN,NaN,outdoor,NaN,NaN,moderate,"75,024",Grass,NaN,NaN,NaN,NaN,NaN,NaN
4,Alltel Stadium,"Jacksonville, FL",NaN,NaN,NaN,NaN,NaN,warm,NaN,NaN,NaN,NaN,30.323889,-81.637500,16.7,6.1

In [6]:
stadiums.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   stadium_name                     120 non-null    object
 1   stadium_location                 119 non-null    object
 2   stadium_open                     90 non-null     float64
 3   stadium_close                    41 non-null     float64
 4   stadium_type                     109 non-null    object
 5   stadium_address                  102 non-null    object
 6   stadium_weather_station_zipcode  101 non-null    object
 7   stadium_weather_type             117 non-null    object
 8   stadium_capacity                 54 non-null     object
 9   stadium_surface                  68 non-null     object
 10  stadium_weather_station          62 non-null     object
 11  stadium_weather_station_name     63 non-null     object
 12  stadium_latitude                 85 non-null     float64
 13  stadium_longitude                85 non-null     float64
 14  stadium_azimuthangle             59 non-null     float64
 15  stadium_elevation                65 non-null     float64
dtypes: float64(6), object(10)
memory usage: 15.1+ KB

In [7]:
games.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
0,9/2/1966,1966,1,False,Miami Dolphins,14.0,23.0,Oakland Raiders,NaN,NaN,NaN,Orange Bowl,False,83.0,6.0,71.0,NaN
1,9/3/1966,1966,1,False,Houston Oilers,45.0,7.0,Denver Broncos,NaN,NaN,NaN,Rice Stadium,False,81.0,7.0,70.0,NaN
2,9/4/1966,1966,1,False,San Diego Chargers,27.0,7.0,Buffalo Bills,NaN,NaN,NaN,Balboa Stadium,False,70.0,7.0,82.0,NaN
3,9/9/1966,1966,2,False,Miami Dolphins,14.0,19.0,New York Jets,NaN,NaN,NaN,Orange Bowl,False,82.0,11.0,78.0,NaN
4,9/10/1966,1966,1,False,Green Bay Packers,24.0,3.0,Baltimore Colts,NaN,NaN,NaN,Lambeau Field,False,64.0,8.0,62.0,NaN

In [8]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13788 entries, 0 to 13787
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   schedule_date        13788 non-null  object
 1   schedule_season      13788 non-null  int64
 2   schedule_week        13788 non-null  object
 3   schedule_playoff     13788 non-null  bool
 4   team_home            13788 non-null  object
 5   score_home           13594 non-null  float64
 6   score_away           13594 non-null  float64
 7   team_away            13788 non-null  object
 8   team_favorite_id     11115 non-null  object
 9   spread_favorite      11115 non-null  float64
 10  over_under_line      11105 non-null  object
 11  stadium              13788 non-null  object
 12  stadium_neutral      13788 non-null  bool
 13  weather_temperature  12410 non-null  float64
 14  weather_wind_mph     12394 non-null  float64
 15  weather_humidity     8468 non-null   float64
 16  weather_detail       3020 non-null   object
dtypes: bool(2), float64(6), int64(1), object(8)
memory usage: 1.6+ MB

In [9]:
teams.head()

,team_name,team_name_short,team_id,team_id_pfr,team_conference,team_division,team_conference_pre2002,team_division_pre2002
0,Arizona Cardinals,Cardinals,ARI,CRD,NFC,NFC West,NFC,NFC West
1,Atlanta Falcons,Falcons,ATL,ATL,NFC,NFC South,NFC,NFC West
2,Baltimore Colts,Colts,IND,CLT,AFC,NaN,AFC,AFC East
3,Baltimore Ravens,Ravens,BAL,RAV,AFC,AFC North,AFC,AFC Central
4,Boston Patriots,Patriots,NE,NWE,AFC,NaN,AFC,NaN

In [10]:
teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   team_name                44 non-null     object
 1   team_name_short          44 non-null     object
 2   team_id                  44 non-null     object
 3   team_id_pfr              44 non-null     object
 4   team_conference          44 non-null     object
 5   team_division            35 non-null     object
 6   team_conference_pre2002  44 non-null     object
 7   team_division_pre2002    42 non-null     object
dtypes: object(8)
memory usage: 2.9+ KB

In [11]:
'''Change data types to Int64'''
stadiums.stadium_capacity = stadiums.stadium_capacity.replace(',','', regex=True)
stadiums.stadium_capacity = stadiums.stadium_capacity.astype("Int64")
stadiums.stadium_open = stadiums.stadium_open.astype("Int64")
stadiums.stadium_close = stadiums.stadium_close.astype("Int64")

In [12]:
'''Verify datatype change'''
stadiums.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   stadium_name                     120 non-null    object
 1   stadium_location                 119 non-null    object
 2   stadium_open                     90 non-null     Int64
 3   stadium_close                    41 non-null     Int64
 4   stadium_type                     109 non-null    object
 5   stadium_address                  102 non-null    object
 6   stadium_weather_station_zipcode  101 non-null    object
 7   stadium_weather_type             117 non-null    object
 8   stadium_capacity                 54 non-null     Int64
 9   stadium_surface                  68 non-null     object
 10  stadium_weather_station          62 non-null     object
 11  stadium_weather_station_name     63 non-null     object
 12  stadium_latitude                 85 non-null     float64
 13  stadium_longitude                85 non-null     float64
 14  stadium_azimuthangle             59 non-null     float64
 15  stadium_elevation                65 non-null     float64
dtypes: Int64(3), float64(4), object(9)
memory usage: 15.5+ KB


The solar azimuth angle is the azimuth (horizontal angle with respect to north) of the Sun's position. This horizontal coordinate defines the Sun's relative direction along the local horizon, whereas the solar zenith angle (or its complementary angle solar elevation) defines the Sun's apparent altitude.

In [13]:
'''Create column for game winner'''
#establish who won each game
winners = []

#iterate through games compariong scores to determine winners, append the winner to the list
for i,v in games.score_home.items():
    if games.score_home[i] > games.score_away[i]:
        winners.append('Home')
        
    elif games.score_away[i]>games.score_home[i]:
        winners.append('Away')
        
    else:
        winners.append("Tie")
        
#convert list to column                       
games["winner"] = winners

In [14]:
'''Create column for game winner'''
#establish who won each game
losers = []

#iterate through games compariong scores to determine winners, append the winner to the list
for i,v in games.score_home.items():
    if games.score_home[i] < games.score_away[i]:
        losers.append('Home')
        
    elif games.score_away[i]<games.score_home[i]:
        losers.append('Away')
        
    else:
        losers.append("Tie")
        
#convert list to column                       
games["loser"] = losers

In [15]:
'''Change team_favorite_id to full name to match the team_home and team_away columns'''
games['team_favorite_id'] = games.team_favorite_id.map(teams.set_index('team_id')['team_name'].to_dict())

In [16]:
'''Verify changes'''
games[games['team_favorite_id'].notnull()]

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail,winner,loser
170,1/15/1967,1966,Superbowl,True,Green Bay Packers,35.0,10.0,Kansas City Chiefs,Green Bay Packers,-14.0,NaN,Los Angeles Memorial Coliseum,True,54.0,7.0,90.0,NaN,Home,Away
350,1/14/1968,1967,Superbowl,True,Green Bay Packers,33.0,14.0,Oakland Raiders,Green Bay Packers,-13.5,43,Orange Bowl,True,60.0,12.0,74.0,NaN,Home,Away
538,1/12/1969,1968,Superbowl,True,Baltimore Colts,7.0,16.0,New York Jets,Indianapolis Colts,-18.0,40,Orange Bowl,True,66.0,12.0,80.0,rain,Away,Home
727,1/11/1970,1969,Superbowl,True,Kansas City Chiefs,23.0,7.0,Minnesota Vikings,Minnesota Vikings,-12.0,39,Tulane Stadium,True,55.0,14.0,84.0,rain,Home,Away
916,1/17/1971,1970,Superbowl,True,Baltimore Colts,16.0,13.0,Dallas Cowboys,Indianapolis Colts,-2.5,36,Orange Bowl,True,59.0,11.0,60.0,NaN,Home,Away
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13589,10/8/2023,2023,5,False,Minnesota Vikings,20.0,27.0,Kansas City Chiefs,Kansas City Chiefs,-3.5,52.5,U.S. Bank Stadium,False,72.0,0.0,NaN,indoor,Away,Home
13590,10/8/2023,2023,5,False,New England Patriots,0.0,34.0,New Orleans Saints,New England Patriots,-1.5,38.5,Gillette Stadium,False,NaN,NaN,NaN,NaN,Away,Home
13591,10/8/2023,2023,5,False,Pittsburgh Steelers,17.0,10.0,Baltimore Ravens,Baltimore Ravens,-4.5,38.5,Acrisure Stadium,False,NaN,NaN,NaN,NaN,Home,Away
13592,10/8/2023,2023,5,False,San Francisco 49ers,42.0,10.0,Dallas Cowboys,San Francisco 49ers,-3.5,45.5,Levi's Stadium,False,NaN,NaN,NaN,NaN,Home,Away
13593,10/9/2023,2023,5,False,Las Vegas Raiders,17.0,13.0,Green Bay Packers,Oakland Raiders,-2.0,45,Allegiant Stadium,False,72.0,0.0,NaN,indoor,Home,Away

In [17]:
games.schedule_week.unique()

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', 'Conference', 'Superbowl', '17',
       'Division', 'Wildcard', '18'], dtype=object)

In [18]:
'''Change Text values of schedule week to int for future use in correlation matrix'''

week_mapping = {
    'Wildcard': 19,
    'Division': 20,
    'Conference': 21,
    'Superbowl': 22
}
# Replace values in the schedule_week column using the mapping
games['schedule_week'] = games['schedule_week'].replace(week_mapping)
# Convert the schedule_week column to a numeric data type (integer)
games['schedule_week'] = pd.to_numeric(games['schedule_week'], errors='coerce')
# Sort the dataframe in ascending order by schedule_season and schedule_week
sorted_games = games.sort_values(by=['schedule_season', 'schedule_week'], ascending=True)

In [19]:
games.schedule_week.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 21,
       22, 17, 20, 19, 18])

In [20]:
'''Creation of columns for score difference and total and correction of spread favorite 
to match standard understanding of spread'''

games['score_difference'] = games['score_away'] - games['score_home']
games['score_total'] = games['score_away'] + games['score_home']

games['spread_favorite'] = np.where(games['team_favorite_id'] == games['team_away'],
                                       np.abs(games['spread_favorite']), games['spread_favorite'])

In [21]:
'''Verify the use of weather_detail to contain info about precipitation'''
games.weather_detail.unique().tolist()

[nan,
 'indoor',
 'rain',
 'rain | fog',
 'fog',
 'snow',
 'retractable (open roof)',
 'snow | fog',
 'snow | Freezing rain']

In [22]:
'''Change null values to indicate no precipitation'''
games['weather_detail'].fillna('No Precip', inplace = True)

In [23]:
'''Merge stadiums and games dataframes on stadium name'''

merged_df = games.merge(stadiums, left_on="stadium",
                       right_on="stadium_name", suffixes=['_x', '_y'], how="left")

merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13788 entries, 0 to 13787
Data columns (total 37 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   schedule_date                    13788 non-null  object
 1   schedule_season                  13788 non-null  int64
 2   schedule_week                    13788 non-null  int64
 3   schedule_playoff                 13788 non-null  bool
 4   team_home                        13788 non-null  object
 5   score_home                       13594 non-null  float64
 6   score_away                       13594 non-null  float64
 7   team_away                        13788 non-null  object
 8   team_favorite_id                 10971 non-null  object
 9   spread_favorite                  11115 non-null  float64
 10  over_under_line                  11105 non-null  object
 11  stadium                          13788 non-null  object
 12  stadium_neutral                  13788 non-null  bool
 13  weather_temperature              12410 non-null  float64
 14  weather_wind_mph                 12394 non-null  float64
 15  weather_humidity                 8468 non-null   float64
 16  weather_detail                   13788 non-null  object
 17  winner                           13788 non-null  object
 18  loser                            13788 non-null  object
 19  score_difference                 13594 non-null  float64
 20  score_total                      13594 non-null  float64
 21  stadium_name                     13788 non-null  object
 22  stadium_location                 13787 non-null  object
 23  stadium_open                     13238 non-null  Int64
 24  stadium_close                    6316 non-null   Int64
 25  stadium_type                     13751 non-null  object
 26  stadium_address                  13541 non-null  object
 27  stadium_weather_station_zipcode  13538 non-null  object
 28  stadium_weather_type             13767 non-null  object
 29  stadium_capacity                 7484 non-null   Int64
 30  stadium_surface                  7936 non-null   object
 31  stadium_weather_station          10511 non-null  object
 32  stadium_weather_station_name     10513 non-null  object
 33  stadium_latitude                 11813 non-null  float64
 34  stadium_longitude                11813 non-null  float64
 35  stadium_azimuthangle             8857 non-null   float64
 36  stadium_elevation                10509 non-null  float64
dtypes: Int64(3), bool(2), float64(12), int64(2), object(18)
memory usage: 3.7+ MB

In [24]:
'''Select desired columns and fill in null values using appropriate method'''

merged_df = merged_df[['schedule_date', 'schedule_season', 'schedule_week', 'schedule_playoff', 
                       'team_home', 'team_away', 'score_home', 'score_away', 'winner', 'loser', 'spread_favorite', 'score_difference', 'score_total'
                       ,'stadium', 'stadium_neutral', 'stadium_type', 'stadium_elevation',
                      'weather_temperature', 'weather_wind_mph', 'weather_detail', 'weather_humidity']]

merged_df = merged_df.dropna(subset=['score_home'])
merged_df = merged_df.dropna(subset=['stadium_type'])
merged_df = merged_df.dropna(subset=['spread_favorite'])

mean_humidity = merged_df['weather_humidity'].mean()
merged_df["weather_humidity"].fillna(mean_humidity, inplace = True)

mean_temp = merged_df['weather_temperature'].mean()
merged_df["weather_temperature"].fillna(mean_temp, inplace = True)

mean_wind = merged_df['weather_wind_mph'].mean()
merged_df["weather_wind_mph"].fillna(mean_wind, inplace = True)



mean_elevation = merged_df['stadium_elevation'].mean()
merged_df["stadium_elevation"].fillna(mean_elevation, inplace = True)

In [25]:
'''Check null values after imputation'''

merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11098 entries, 170 to 13593
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   schedule_date        11098 non-null  object
 1   schedule_season      11098 non-null  int64
 2   schedule_week        11098 non-null  int64
 3   schedule_playoff     11098 non-null  bool
 4   team_home            11098 non-null  object
 5   team_away            11098 non-null  object
 6   score_home           11098 non-null  float64
 7   score_away           11098 non-null  float64
 8   winner               11098 non-null  object
 9   loser                11098 non-null  object
 10  spread_favorite      11098 non-null  float64
 11  score_difference     11098 non-null  float64
 12  score_total          11098 non-null  float64
 13  stadium              11098 non-null  object
 14  stadium_neutral      11098 non-null  bool
 15  stadium_type         11098 non-null  object
 16  stadium_elevation    11098 non-null  float64
 17  weather_temperature  11098 non-null  float64
 18  weather_wind_mph     11098 non-null  float64
 19  weather_detail       11098 non-null  object
 20  weather_humidity     11098 non-null  float64
dtypes: bool(2), float64(9), int64(2), object(8)
memory usage: 1.7+ MB

In [26]:
'''Check for duplicated values'''

duplicate_values = merged_df.duplicated().sum()
print(duplicate_values)

0

In [27]:
merged_df.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,team_away,score_home,score_away,winner,loser,...,score_difference,score_total,stadium,stadium_neutral,stadium_type,stadium_elevation,weather_temperature,weather_wind_mph,weather_detail,weather_humidity
170,1/15/1967,1966,22,True,Green Bay Packers,Kansas City Chiefs,35.0,10.0,Home,Away,...,-25.0,45.0,Los Angeles Memorial Coliseum,True,outdoor,29.60000,54.0,7.0,No Precip,90.0
350,1/14/1968,1967,22,True,Green Bay Packers,Oakland Raiders,33.0,14.0,Home,Away,...,-19.0,47.0,Orange Bowl,True,outdoor,8.80000,60.0,12.0,No Precip,74.0
538,1/12/1969,1968,22,True,Baltimore Colts,New York Jets,7.0,16.0,Away,Home,...,9.0,23.0,Orange Bowl,True,outdoor,8.80000,66.0,12.0,rain,80.0
727,1/11/1970,1969,22,True,Kansas City Chiefs,Minnesota Vikings,23.0,7.0,Home,Away,...,-16.0,30.0,Tulane Stadium,True,outdoor,184.10755,55.0,14.0,rain,84.0
916,1/17/1971,1970,22,True,Baltimore Colts,Dallas Cowboys,16.0,13.0,Home,Away,...,-3.0,29.0,Orange Bowl,True,outdoor,8.80000,59.0,11.0,No Precip,60.0

In [28]:
merged_df.describe(include="all")

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,team_away,score_home,score_away,winner,loser,...,score_difference,score_total,stadium,stadium_neutral,stadium_type,stadium_elevation,weather_temperature,weather_wind_mph,weather_detail,weather_humidity
count,11098,11098.000000,11098.000000,11098,11098,11098,11098.000000,11098.000000,11098,11098,...,11098.000000,11098.000000,11098,11098,11098,11098.000000,11098.000000,11098.000000,11098,11098.000000
unique,2117,NaN,NaN,2,43,43,NaN,NaN,3,3,...,NaN,NaN,92,2,3,NaN,NaN,NaN,9,NaN
top,1/3/2010,NaN,NaN,False,San Francisco 49ers,Pittsburgh Steelers,NaN,NaN,Home,Away,...,NaN,NaN,Giants Stadium,False,outdoor,NaN,NaN,NaN,No Precip,NaN
freq,16,NaN,NaN,10612,383,374,NaN,NaN,6380,6380,...,NaN,NaN,502,11004,8417,NaN,NaN,NaN,8298,NaN
mean,NaN,2001.592269,9.505316,NaN,NaN,NaN,22.760768,20.093711,NaN,NaN,...,-2.667057,42.854478,NaN,NaN,NaN,184.107550,60.058759,7.107827,NaN,66.572660
std,NaN,12.691542,5.358300,NaN,NaN,NaN,10.354768,10.070002,NaN,NaN,...,14.599667,14.286427,NaN,NaN,NaN,285.644639,14.700164,5.496145,NaN,12.186784
min,NaN,1966.000000,1.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,-59.000000,3.000000,NaN,NaN,NaN,1.800000,-6.000000,0.000000,NaN,4.000000
25%,NaN,1991.000000,5.000000,NaN,NaN,NaN,16.000000,13.000000,NaN,NaN,...,-11.000000,33.000000,NaN,NaN,NaN,13.400000,51.000000,1.000000,NaN,66.000000
50%,NaN,2002.000000,10.000000,NaN,NaN,NaN,23.000000,20.000000,NaN,NaN,...,-3.000000,42.000000,NaN,NaN,NaN,178.000000,61.000000,7.107827,NaN,66.572660
75%,NaN,2013.000000,14.000000,NaN,NaN,NaN,30.000000,27.000000,NaN,NaN,...,6.000000,52.000000,NaN,NaN,NaN,193.900000,72.000000,10.000000,NaN,71.000000
max,NaN,2023.000000,22.000000,NaN,NaN,NaN,70.000000,59.000000,NaN,NaN,...,51.000000,106.000000,NaN,NaN,NaN,1611.200000,97.000000,40.000000,NaN,100.000000

In [29]:
merged_df.to_csv("cleaned_data/games_1.csv")

In [30]:
#stadiums = stadiums.drop(columns=['stadium_weather_station_zipcode', 'stadium_weather_station',
                       #'stadium_weather_station_name', 'stadium_azimuthangle'])
#stadiums.head()

In [31]:
#stadiums[stadiums['stadium_surface'].isnull()]

In [32]:
#stadiums.to_csv("cleaned_data/stadiums_1.csv")