In [1]:
# import os
# kaggle_data={"username":"","key":""}
# os.environ['KAGGLE_USERNAME']=kaggle_data["username"]
# os.environ['KAGGLE_KEY']=kaggle_data["key"]

In [ ]:
kaggle datasets download -d tobycrabtree/nfl-scores-and-betting-data_s

In [1]:
import pandas as pd
import numpy as np
#import kaggle

In [3]:
#kaggle.api.dataset_download_files("tobycrabtree/nfl-scores-and-betting-data", path="./", unzip=True, quiet=False)

In [2]:
teams = pd.read_csv("data/nfl_teams.csv")
stadiums = pd.read_csv("data/nfl_stadiums.csv", encoding='unicode_escape')
games =  pd.read_csv("data/spreadspoke_scores.csv")

In [3]:
teams.head()

,team_name,team_name_short,team_id,team_id_pfr,team_conference,team_division,team_conference_pre2002,team_division_pre2002
0,Arizona Cardinals,Cardinals,ARI,CRD,NFC,NFC West,NFC,NFC West
1,Atlanta Falcons,Falcons,ATL,ATL,NFC,NFC South,NFC,NFC West
2,Baltimore Colts,Colts,IND,CLT,AFC,NaN,AFC,AFC East
3,Baltimore Ravens,Ravens,BAL,RAV,AFC,AFC North,AFC,AFC Central
4,Boston Patriots,Patriots,NE,NWE,AFC,NaN,AFC,NaN

In [7]:
teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   team_name                44 non-null     object
 1   team_name_short          44 non-null     object
 2   team_id                  44 non-null     object
 3   team_id_pfr              44 non-null     object
 4   team_conference          44 non-null     object
 5   team_division            35 non-null     object
 6   team_conference_pre2002  44 non-null     object
 7   team_division_pre2002    42 non-null     object
dtypes: object(8)
memory usage: 2.9+ KB

In [4]:
stadiums.head()

,stadium_name,stadium_location,stadium_open,stadium_close,stadium_type,stadium_address,stadium_weather_station_zipcode,stadium_weather_type,stadium_capacity,stadium_surface,stadium_weather_station,stadium_weather_station_name,stadium_latitude,stadium_longitude,stadium_azimuthangle,stadium_elevation
0,Acrisure Stadium,"Pittsburgh, PA",2001.0,NaN,outdoor,"100 Art Rooney Ave, Pittsburgh, PA 15212",15212,cold,"65,500",Grass,USW00094823,"PITTSBURGH ASOS, PA US",40.484600,-80.214400,NaN,366.7
1,Alamo Dome,"San Antonio, TX",NaN,NaN,indoor,"100 Montana St, San Antonio, TX 78203",78203,indoor,72000,FieldTurf,NaN,NaN,29.416944,-98.478889,0.0,NaN
2,Allegiant Stadium,"Paradise, NV",2020.0,NaN,indoor,NaN,NaN,indoor,65000,Grass,NaN,NaN,36.090750,-115.183722,0.0,NaN
3,Allianz Arena,"Munich, Germany",NaN,NaN,outdoor,NaN,NaN,moderate,"75,024",Grass,NaN,NaN,NaN,NaN,NaN,NaN
4,Alltel Stadium,"Jacksonville, FL",NaN,NaN,NaN,NaN,NaN,warm,NaN,NaN,NaN,NaN,30.323889,-81.637500,16.7,6.1

In [6]:
stadiums.stadium_surface.unique().tolist()

['Grass',
 'FieldTurf',
 nan,
 'Grass, Turf (1970-1971)',
 'Grass, Turf (1969-1970)',
 'Hellas Matrix Turf',
 'Grass, Turf (1971-1974)']

In [7]:
games.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,score_home,score_away,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
0,9/2/1966,1966,1,False,Miami Dolphins,14.0,23.0,Oakland Raiders,NaN,NaN,NaN,Orange Bowl,False,83.0,6.0,71.0,NaN
1,9/3/1966,1966,1,False,Houston Oilers,45.0,7.0,Denver Broncos,NaN,NaN,NaN,Rice Stadium,False,81.0,7.0,70.0,NaN
2,9/4/1966,1966,1,False,San Diego Chargers,27.0,7.0,Buffalo Bills,NaN,NaN,NaN,Balboa Stadium,False,70.0,7.0,82.0,NaN
3,9/9/1966,1966,2,False,Miami Dolphins,14.0,19.0,New York Jets,NaN,NaN,NaN,Orange Bowl,False,82.0,11.0,78.0,NaN
4,9/10/1966,1966,1,False,Green Bay Packers,24.0,3.0,Baltimore Colts,NaN,NaN,NaN,Lambeau Field,False,64.0,8.0,62.0,NaN

In [8]:
stadiums.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   stadium_name                     120 non-null    object
 1   stadium_location                 119 non-null    object
 2   stadium_open                     90 non-null     float64
 3   stadium_close                    41 non-null     float64
 4   stadium_type                     109 non-null    object
 5   stadium_address                  102 non-null    object
 6   stadium_weather_station_zipcode  101 non-null    object
 7   stadium_weather_type             117 non-null    object
 8   stadium_capacity                 54 non-null     object
 9   stadium_surface                  68 non-null     object
 10  stadium_weather_station          62 non-null     object
 11  stadium_weather_station_name     63 non-null     object
 12  stadium_latitude                 85 non-null     float64
 13  stadium_longitude                85 non-null     float64
 14  stadium_azimuthangle             59 non-null     float64
 15  stadium_elevation                65 non-null     float64
dtypes: float64(6), object(10)
memory usage: 15.1+ KB

In [9]:
stadiums.stadium_capacity = stadiums.stadium_capacity.replace(',','', regex=True)
stadiums.stadium_capacity = stadiums.stadium_capacity.astype("Int64")
stadiums.stadium_open = stadiums.stadium_open.astype("Int64")
stadiums.stadium_close = stadiums.stadium_close.astype("Int64")

In [10]:
stadiums.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   stadium_name                     120 non-null    object
 1   stadium_location                 119 non-null    object
 2   stadium_open                     90 non-null     Int64
 3   stadium_close                    41 non-null     Int64
 4   stadium_type                     109 non-null    object
 5   stadium_address                  102 non-null    object
 6   stadium_weather_station_zipcode  101 non-null    object
 7   stadium_weather_type             117 non-null    object
 8   stadium_capacity                 54 non-null     Int64
 9   stadium_surface                  68 non-null     object
 10  stadium_weather_station          62 non-null     object
 11  stadium_weather_station_name     63 non-null     object
 12  stadium_latitude                 85 non-null     float64
 13  stadium_longitude                85 non-null     float64
 14  stadium_azimuthangle             59 non-null     float64
 15  stadium_elevation                65 non-null     float64
dtypes: Int64(3), float64(4), object(9)
memory usage: 15.5+ KB


The solar azimuth angle is the azimuth (horizontal angle with respect to north) of the Sun's position. This horizontal coordinate defines the Sun's relative direction along the local horizon, whereas the solar zenith angle (or its complementary angle solar elevation) defines the Sun's apparent altitude.

In [11]:
#establish who won each game
winners = []

#iterate through games compariong scores to determine winners, append the winner to the list
for i,v in games.score_home.items():
    if games.score_home[i] > games.score_away[i]:
        winners.append(games.team_home[i])
        
    elif games.score_away[i]>games.score_home[i]:
        winners.append(games.team_away[i])
        
    else:
        winners.append("Tie")
        
#convert list to column                       
games["winner"] = winners

In [12]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13788 entries, 0 to 13787
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   schedule_date        13788 non-null  object
 1   schedule_season      13788 non-null  int64
 2   schedule_week        13788 non-null  object
 3   schedule_playoff     13788 non-null  bool
 4   team_home            13788 non-null  object
 5   score_home           13594 non-null  float64
 6   score_away           13594 non-null  float64
 7   team_away            13788 non-null  object
 8   team_favorite_id     11115 non-null  object
 9   spread_favorite      11115 non-null  float64
 10  over_under_line      11105 non-null  object
 11  stadium              13788 non-null  object
 12  stadium_neutral      13788 non-null  bool
 13  weather_temperature  12410 non-null  float64
 14  weather_wind_mph     12394 non-null  float64
 15  weather_humidity     8468 non-null   float64
 16  weather_detail       3020 non-null   object
 17  winner               13788 non-null  object
dtypes: bool(2), float64(6), int64(1), object(9)
memory usage: 1.7+ MB

In [8]:
games.weather_detail.unique().tolist()

[nan,
 'indoor',
 'rain',
 'rain | fog',
 'fog',
 'snow',
 'retractable (open roof)',
 'snow | fog',
 'snow | Freezing rain']

In [13]:
merged_df = games.merge(stadiums, left_on="stadium",
                       right_on="stadium_name", suffixes=['_x', '_y'], how="left")

merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13788 entries, 0 to 13787
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   schedule_date                    13788 non-null  object
 1   schedule_season                  13788 non-null  int64
 2   schedule_week                    13788 non-null  object
 3   schedule_playoff                 13788 non-null  bool
 4   team_home                        13788 non-null  object
 5   score_home                       13594 non-null  float64
 6   score_away                       13594 non-null  float64
 7   team_away                        13788 non-null  object
 8   team_favorite_id                 11115 non-null  object
 9   spread_favorite                  11115 non-null  float64
 10  over_under_line                  11105 non-null  object
 11  stadium                          13788 non-null  object
 12  stadium_neutral                  13788 non-null  bool
 13  weather_temperature              12410 non-null  float64
 14  weather_wind_mph                 12394 non-null  float64
 15  weather_humidity                 8468 non-null   float64
 16  weather_detail                   3020 non-null   object
 17  winner                           13788 non-null  object
 18  stadium_name                     13788 non-null  object
 19  stadium_location                 13787 non-null  object
 20  stadium_open                     13238 non-null  Int64
 21  stadium_close                    6316 non-null   Int64
 22  stadium_type                     13751 non-null  object
 23  stadium_address                  13541 non-null  object
 24  stadium_weather_station_zipcode  13538 non-null  object
 25  stadium_weather_type             13767 non-null  object
 26  stadium_capacity                 7484 non-null   Int64
 27  stadium_surface                  7936 non-null   object
 28  stadium_weather_station          10511 non-null  object
 29  stadium_weather_station_name     10513 non-null  object
 30  stadium_latitude                 11813 non-null  float64
 31  stadium_longitude                11813 non-null  float64
 32  stadium_azimuthangle             8857 non-null   float64
 33  stadium_elevation                10509 non-null  float64
dtypes: Int64(3), bool(2), float64(10), int64(1), object(18)
memory usage: 3.4+ MB

In [14]:
merged_df = merged_df.drop(columns=['stadium_open', 'stadium_close', 'stadium_address',
                        'stadium_weather_station_zipcode', 'stadium_capacity', 'stadium_weather_station',
                       'stadium_weather_station_name', 'stadium_azimuthangle', 'stadium_name',
                                   'stadium_weather_type', 'stadium_location', 'stadium_latitude',
                                   'stadium_longitude'])
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13788 entries, 0 to 13787
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   schedule_date        13788 non-null  object
 1   schedule_season      13788 non-null  int64
 2   schedule_week        13788 non-null  object
 3   schedule_playoff     13788 non-null  bool
 4   team_home            13788 non-null  object
 5   score_home           13594 non-null  float64
 6   score_away           13594 non-null  float64
 7   team_away            13788 non-null  object
 8   team_favorite_id     11115 non-null  object
 9   spread_favorite      11115 non-null  float64
 10  over_under_line      11105 non-null  object
 11  stadium              13788 non-null  object
 12  stadium_neutral      13788 non-null  bool
 13  weather_temperature  12410 non-null  float64
 14  weather_wind_mph     12394 non-null  float64
 15  weather_humidity     8468 non-null   float64
 16  weather_detail       3020 non-null   object
 17  winner               13788 non-null  object
 18  stadium_type         13751 non-null  object
 19  stadium_surface      7936 non-null   object
 20  stadium_elevation    10509 non-null  float64
dtypes: bool(2), float64(7), int64(1), object(11)
memory usage: 2.0+ MB

In [15]:
merged_df = merged_df[['schedule_date', 'schedule_season', 'schedule_week', 'schedule_playoff', 
                       'team_home', 'team_away', 'score_home', 'score_away', 'winner', 'team_favorite_id',
                      'spread_favorite', 'over_under_line', 
                       'stadium', 'stadium_neutral', 'stadium_type', 'stadium_surface', 'stadium_elevation',
                      'weather_temperature', 'weather_wind_mph', 'weather_humidity', 'weather_detail']]
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13788 entries, 0 to 13787
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   schedule_date        13788 non-null  object
 1   schedule_season      13788 non-null  int64
 2   schedule_week        13788 non-null  object
 3   schedule_playoff     13788 non-null  bool
 4   team_home            13788 non-null  object
 5   team_away            13788 non-null  object
 6   score_home           13594 non-null  float64
 7   score_away           13594 non-null  float64
 8   winner               13788 non-null  object
 9   team_favorite_id     11115 non-null  object
 10  spread_favorite      11115 non-null  float64
 11  over_under_line      11105 non-null  object
 12  stadium              13788 non-null  object
 13  stadium_neutral      13788 non-null  bool
 14  stadium_type         13751 non-null  object
 15  stadium_surface      7936 non-null   object
 16  stadium_elevation    10509 non-null  float64
 17  weather_temperature  12410 non-null  float64
 18  weather_wind_mph     12394 non-null  float64
 19  weather_humidity     8468 non-null   float64
 20  weather_detail       3020 non-null   object
dtypes: bool(2), float64(7), int64(1), object(11)
memory usage: 2.0+ MB

In [16]:
pd.set_option('display.max_columns', 500)
merged_df.head()

,schedule_date,schedule_season,schedule_week,schedule_playoff,team_home,team_away,score_home,score_away,winner,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,stadium_type,stadium_surface,stadium_elevation,weather_temperature,weather_wind_mph,weather_humidity,weather_detail
0,9/2/1966,1966,1,False,Miami Dolphins,Oakland Raiders,14.0,23.0,Oakland Raiders,NaN,NaN,NaN,Orange Bowl,False,outdoor,NaN,8.8,83.0,6.0,71.0,NaN
1,9/3/1966,1966,1,False,Houston Oilers,Denver Broncos,45.0,7.0,Houston Oilers,NaN,NaN,NaN,Rice Stadium,False,outdoor,Grass,NaN,81.0,7.0,70.0,NaN
2,9/4/1966,1966,1,False,San Diego Chargers,Buffalo Bills,27.0,7.0,San Diego Chargers,NaN,NaN,NaN,Balboa Stadium,False,outdoor,Grass,NaN,70.0,7.0,82.0,NaN
3,9/9/1966,1966,2,False,Miami Dolphins,New York Jets,14.0,19.0,New York Jets,NaN,NaN,NaN,Orange Bowl,False,outdoor,NaN,8.8,82.0,11.0,78.0,NaN
4,9/10/1966,1966,1,False,Green Bay Packers,Baltimore Colts,24.0,3.0,Green Bay Packers,NaN,NaN,NaN,Lambeau Field,False,outdoor,Grass,209.4,64.0,8.0,62.0,NaN

In [17]:
stadiums = stadiums.drop(columns=['stadium_weather_station_zipcode', 'stadium_weather_station',
                       'stadium_weather_station_name', 'stadium_azimuthangle'])
stadiums.head()

,stadium_name,stadium_location,stadium_open,stadium_close,stadium_type,stadium_address,stadium_weather_type,stadium_capacity,stadium_surface,stadium_latitude,stadium_longitude,stadium_elevation
0,Acrisure Stadium,"Pittsburgh, PA",2001,<NA>,outdoor,"100 Art Rooney Ave, Pittsburgh, PA 15212",cold,65500,Grass,40.484600,-80.214400,366.7
1,Alamo Dome,"San Antonio, TX",<NA>,<NA>,indoor,"100 Montana St, San Antonio, TX 78203",indoor,72000,FieldTurf,29.416944,-98.478889,NaN
2,Allegiant Stadium,"Paradise, NV",2020,<NA>,indoor,NaN,indoor,65000,Grass,36.090750,-115.183722,NaN
3,Allianz Arena,"Munich, Germany",<NA>,<NA>,outdoor,NaN,moderate,75024,Grass,NaN,NaN,NaN
4,Alltel Stadium,"Jacksonville, FL",<NA>,<NA>,NaN,NaN,warm,<NA>,NaN,30.323889,-81.637500,6.1

In [18]:
stadiums.to_csv("cleaned_data/stadiums_1.csv")

In [19]:
merged_df.to_csv("cleaned_data/games_1.csv")